//get all needed user data
GET http://localhost:3000/api/users/getAllUsers

###

//add age, gender, about me and contact to user profile

POST http://localhost:3000/api/users/loginForm
Content-Type: application/json 

{
  "user": {	
      "email": "pong",
      "age": 99,
      "gender": "male",
      "about": "ping",
      "contact" : "11 1234 5678",
      "interests": ["skateboarding", "baseball", "movies", "anime", "basketball", "martial_arts", "gaming", "music", "writing", "programming", "cooking", "gardening", "fishing", "politics"]
  }
}

###

GET http://localhost:3000/api/users/ownUserTags
Cookie: next-auth.csrf-token=e271d0db91609a1b4ee50b1c1aed809574cae76d83a14041eef7550a0673c253|ec2c218d34a404f523d71be0d7093a697d55ffb14d38ae233cc034fda4c7bbad; next-auth.session-token=62fcb508-2c2a-4ad7-9016-7df0a03e2dcd


###

POST http://localhost:3000/api/users/ownUserTags
Content-Type: application/json
Cookie: next-auth.csrf-token=e271d0db91609a1b4ee50b1c1aed809574cae76d83a14041eef7550a0673c253|ec2c218d34a404f523d71be0d7093a697d55ffb14d38ae233cc034fda4c7bbad; next-auth.session-token=62fcb508-2c2a-4ad7-9016-7df0a03e2dcd

{
  "tags": ["anime", "basketball", "movies"]
}

###

POST http://localhost:3000/api/users/likedTags
Content-Type: application/json
Cookie: next-auth.csrf-token=e271d0db91609a1b4ee50b1c1aed809574cae76d83a14041eef7550a0673c253|ec2c218d34a404f523d71be0d7093a697d55ffb14d38ae233cc034fda4c7bbad; next-auth.session-token=62fcb508-2c2a-4ad7-9016-7df0a03e2dcd

{
  "tags": ["anime", "basketball", "movies"]
}

###

POST http://localhost:3000/api/tagSearch
Content-Type: application/json

{
  "searchTags": ["anime", "basketball", "movies"]
}

###

POST http://localhost:3000/api/users/getUserProfile
Content-Type: application/json

{
  "id": "clw08wg880000wb4z3eibd3ir"
}

###

POST http://localhost:3000/api/match/create
Content-Type: application/json

{
  "requesterId": "clw08wg880000wb4z3eibd3ir",
  "receiverId": "clx8vwas10000ch77tqvmd9kz"
}

###

POST http://localhost:3000/api/match/response
Content-Type: application/json

{
  "matchRequestId": "cm0lcmayo0001tvto1sz5jrmh",
  "action": "accept"
}

###

POST http://localhost:3000/api/match/response
Content-Type: application/json

{
  "matchRequestId": "cm0lcmayo0001tvto1sz5jrmh",
  "action": "deny"
}