//get all needed user data
GET http://localhost:3000/api/users/getAllUsers

###

//add age, gender, about me and contact to user profile

POST http://localhost:3000/api/users/loginForm
Content-Type: application/json 

{
    "user": {	
        "email": "pong",
        "age": 99,
        "gender": "male",
        "about": "ping",
        "contact" : "11 1234 5678"
    }
}

###

GET http://localhost:3000/api/users/ownUserTags
Cookie: next-auth.callback-url=http://localhost:3000/google-signin; next-auth.csrf-token=f554387842e9444b55d1ed7f70e39480a065792c4e1b39fd5de7d01394348d04|d3c39793addb41c7f3335900816f51083556156a6c237a9d97932247aa74450b; next-auth.session-token=60f2b222-be16-4b09-b5f2-6b28d0fbade4


###

POST http://localhost:3000/api/users/ownUserTags
Content-Type: application/json
Cookie: next-auth.callback-url=http://localhost:3000/google-signin; next-auth.csrf-token=f554387842e9444b55d1ed7f70e39480a065792c4e1b39fd5de7d01394348d04|d3c39793addb41c7f3335900816f51083556156a6c237a9d97932247aa74450b; next-auth.session-token=60f2b222-be16-4b09-b5f2-6b28d0fbade4

{
  "tag": "basketball"
}

###

POST http://localhost:3000/api/tagSearch
Content-Type: application/json

{
  "searchTags": ["anime", "basketball"]
}